import os
os.environ["CUDA_VISIBLE_DEVICES"]='0'
import numpy as np
import time
import pickle
import sys
import argparse
from ppl_utils.bias_utils import *
import csv
import copy
import random
import re
from tqdm import trange
import itertools
import openai
from ppl_utils.utils import *
import json





if __name__ == "__main__":

    input_path='./motivation_prompt.pkl'
    model='gemini-1.5-Flash-001' # 
    # model='3.5' # GPT-3.5-Turbo
    save_path='./result.json'
    repeat_num=5

    # step 1: Construct dataset using LLMs.
    dataset_path='../dataset/dataset.pkl'
    with open(dataset_path, 'rb') as f:#input,bug type,params
        prompt_dict = pickle.load(f)

    with open(input_path, 'rb') as f:#input,bug type,params
        message = pickle.load(f)

    input_code=message[1]['content'].split('code:')[-1]

    result_save_path=save_path

    if os.path.exists(result_save_path):
        with open(result_save_path, 'r') as json_file:
            result_log_dict=json.load(json_file)
    else:
        result_log_dict={}
    if model not in result_log_dict.keys():
        result_log_dict[model]={}
    for r in range(repeat_num):
        result_key=f'{r}'
        if result_key in result_log_dict[model].keys():
            continue

        if str(r) not in result_log_dict.keys():
            llm_response=query_llm(None,None,sleep=1,message_text=message,version=model)
            result_log_dict[model][str(r)]=llm_response
            with open(result_save_path, 'w') as json_file:
                json.dump(result_log_dict, json_file, indent=4) 
        else:
            llm_response=result_log_dict[model][str(r)]

        print('Input Code:')
        print(input_code)
        print('-----------')
        print(f'Code Generated by {model}:')
        print(llm_response)
        print('-----------')
    print(1)